networks:
  internal:
services:
  db:
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
    image: postgres:11
    networks:
      - internal
    ports:
      - '5432:5432'
    restart: unless-stopped
  web:
    build: .
    command: ./bin/touch_me start
    environment:
      APP_PORT: ${APP_PORT}
      APP_HOSTNAME: ${APP_HOSTNAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      DB_HOSTNAME: ${DATABASE_HOST}
    depends_on:
      - db
    networks:
      - internal
    ports:
      - '4000:4000'
    restart: unless-stopped
version: '3'
